# Generated by Django 2.2.4 on 2019-10-31 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_vtuber',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('liver_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('twitter_id', models.CharField(max_length=100)),
                ('src', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vtuber',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('liver_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('src', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='On_Live',
            fields=[
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Vtuber', unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('live_title', models.CharField(max_length=100)),
                ('live_url', models.CharField(max_length=100)),
            ],
        ),
    ]
