# Generated by Django 2.2.4 on 2019-10-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_vtuber',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('liver_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
